- name: test playbook
  hosts: all
  tasks:
    - name: Shell command
      shell: "ip a && hostname && id"
      register: __shell_output

    - name: output shell
      debug:
        msg: "{{ __shell_output }}"

