- name: test playbook
  hosts: all
  tasks:
    - name: Shell command
      shell: "hostname"
      register: __shell_output

    - name: output shell
      debug:
        msg: "{{ __shell_output.stdout }}"

